// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UQ.Api.Infrastructure;
using UQ.Api.Infrastructure.Data;

#nullable disable

namespace UQ.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226164032_AddFailedTable")]
    partial class AddFailedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UQ.Api.Infrastructure.MessageModels.MessageBody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BodyValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MessageBodies");
                });

            modelBuilder.Entity("UQ.Api.Infrastructure.MessageModels.MessageHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("HeaderKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeaderValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MessageHeaders");
                });

            modelBuilder.Entity("UQ.Api.Infrastructure.MessageModels.MinimalMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("CallerRequestId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DestinationUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ScheduledOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("MinimalMessages");

                    b.HasDiscriminator().HasValue("MinimalMessage");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UQ.Api.Infrastructure.MessageModels.MinimalMessageToRetry", b =>
                {
                    b.HasBaseType("UQ.Api.Infrastructure.MessageModels.MinimalMessage");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MinimalMessageToRetry");
                });

            modelBuilder.Entity("UQ.Api.Infrastructure.MessageModels.FailedMessage", b =>
                {
                    b.HasBaseType("UQ.Api.Infrastructure.MessageModels.MinimalMessageToRetry");

                    b.HasDiscriminator().HasValue("FailedMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
